name: Deploy Staging

on:
  push:
    branches: [ staging ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/efatura-backend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-backend:staging

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-frontend:staging

      - name: Deploy over SSH (optional)
        if: ${{ secrets.STAGING_HOST && secrets.STAGING_USER && secrets.STAGING_KEY }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_KEY }}
          port: ${{ secrets.STAGING_PORT || 22 }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}-backend:staging
            docker pull ghcr.io/${{ github.repository }}-frontend:staging
            docker stop efatura-backend || true
            docker rm efatura-backend || true
            docker stop efatura-frontend || true
            docker rm efatura-frontend || true
            docker run -d --name efatura-backend --env-file /opt/efatura/.env --network efatura-net -p 9000:9000 ghcr.io/${{ github.repository }}-backend:staging
            docker run -d --name efatura-frontend --network efatura-net -p 3000:80 ghcr.io/${{ github.repository }}-frontend:staging

